//! Módulo de recursos da API do GitLab.
//!
//! Este módulo contém todos os recursos (endpoints) da API do GitLab,
//! organizados em arquivos separados por domínio.

mod access_requests;
mod access_tokens;
mod audit_events;
mod badges;
mod boards;
mod branches;
mod broadcast_messages;
mod ci_lint;
mod ci_yml_templates;
mod commits;
mod container_registry;
mod custom_attributes;
mod deploy_keys;
mod deploy_tokens;
mod deployments;
mod discussions;
mod dockerfile_templates;
mod draft_notes;
mod emoji;
mod environments;
mod epics;
mod error_tracking;
mod events;
mod external_status_checks;
mod feature_flags;
mod freeze_periods;
mod gitignore_templates;
mod group_iterations;
mod group_push_rules;
mod group_variables;
mod group_webhooks;
mod group_wikis;
mod groups;
mod import_export;
mod integrations;
mod invitations;
mod issue_links;
mod issues;
mod issues_statistics;
mod job_artifacts;
mod jobs;
mod keys;
mod labels;
mod license;
mod license_templates;
mod markdown;
mod members;
mod merge_requests;
mod merge_trains;
mod milestones;
mod namespaces;
mod notes;
mod notification_settings;
mod package_composer;
mod package_conan;
mod package_debian;
mod package_go_proxy;
mod package_helm;
mod package_maven;
mod package_npm;
mod package_nuget;
mod package_pypi;
mod package_rubygems;
mod package_terraform_modules;
mod packages;
mod pages;
mod personal_access_tokens;
mod pipeline_schedules;
mod pipeline_triggers;
mod pipelines;
mod project_hooks;
mod project_templates;
mod projects;
mod protected_branches;
mod protected_environments;
mod protected_tags;
mod releases;
mod remote_mirrors;
mod repository_files;
mod repository_tree;
mod resource_events;
mod runners;
mod search;
mod settings;
mod snippets;
mod system_hooks;
mod tags;
mod todos;
mod topics;
mod users;
mod variables;
mod vulnerabilities;
mod wikis;

pub use access_requests::AccessRequestsResource;
pub use access_tokens::AccessTokensResource;
pub use audit_events::AuditEventsResource;
pub use badges::BadgesResource;
pub use boards::BoardsResource;
pub use branches::BranchesResource;
pub use broadcast_messages::BroadcastMessagesResource;
pub use ci_lint::CiLintResource;
pub use ci_yml_templates::CiYmlTemplatesResource;
pub use commits::CommitsResource;
pub use container_registry::ContainerRegistryResource;
pub use custom_attributes::CustomAttributesResource;
pub use deploy_keys::DeployKeysResource;
pub use deploy_tokens::DeployTokensResource;
pub use deployments::DeploymentsResource;
pub use discussions::DiscussionsResource;
pub use dockerfile_templates::DockerfileTemplatesResource;
pub use draft_notes::DraftNotesResource;
pub use emoji::EmojiResource;
pub use environments::EnvironmentsResource;
pub use epics::EpicsResource;
pub use error_tracking::ErrorTrackingResource;
pub use events::EventsResource;
pub use external_status_checks::ExternalStatusChecksResource;
pub use feature_flags::FeatureFlagsResource;
pub use freeze_periods::FreezePeriodsResource;
pub use gitignore_templates::GitignoreTemplatesResource;
pub use group_iterations::GroupIterationsResource;
pub use group_push_rules::GroupPushRulesResource;
pub use group_variables::GroupVariablesResource;
pub use group_webhooks::GroupWebhooksResource;
pub use group_wikis::GroupWikisResource;
pub use groups::GroupsResource;
pub use import_export::ImportExportResource;
pub use integrations::IntegrationsResource;
pub use invitations::InvitationsResource;
pub use issue_links::IssueLinksResource;
pub use issues::IssuesResource;
pub use issues_statistics::IssuesStatisticsResource;
pub use job_artifacts::JobArtifactsResource;
pub use jobs::JobsResource;
pub use keys::KeysResource;
pub use labels::LabelsResource;
pub use license::LicenseResource;
pub use license_templates::LicenseTemplatesResource;
pub use markdown::MarkdownResource;
pub use members::MembersResource;
pub use merge_requests::MergeRequestsResource;
pub use merge_trains::MergeTrainsResource;
pub use milestones::MilestonesResource;
pub use namespaces::NamespacesResource;
pub use notes::NotesResource;
pub use notification_settings::NotificationSettingsResource;
pub use package_composer::PackageComposerResource;
pub use package_conan::PackageConanResource;
pub use package_debian::PackageDebianResource;
pub use package_go_proxy::PackageGoProxyResource;
pub use package_helm::PackageHelmResource;
pub use package_maven::PackageMavenResource;
pub use package_npm::PackageNpmResource;
pub use package_nuget::PackageNugetResource;
pub use package_pypi::PackagePypiResource;
pub use package_rubygems::PackageRubygemsResource;
pub use package_terraform_modules::PackageTerraformModulesResource;
pub use packages::PackagesResource;
pub use pages::PagesResource;
pub use personal_access_tokens::PersonalAccessTokensResource;
pub use pipeline_schedules::PipelineSchedulesResource;
pub use pipeline_triggers::PipelineTriggersResource;
pub use pipelines::PipelinesResource;
pub use project_hooks::ProjectHooksResource;
pub use project_templates::ProjectTemplatesResource;
pub use projects::ProjectsResource;
pub use protected_branches::ProtectedBranchesResource;
pub use protected_environments::ProtectedEnvironmentsResource;
pub use protected_tags::ProtectedTagsResource;
pub use releases::ReleasesResource;
pub use remote_mirrors::RemoteMirrorsResource;
pub use repository_files::RepositoryFilesResource;
pub use repository_tree::RepositoryTreeResource;
pub use resource_events::ResourceEventsResource;
pub use runners::RunnersResource;
pub use search::SearchResource;
pub use settings::SettingsResource;
pub use snippets::SnippetsResource;
pub use system_hooks::SystemHooksResource;
pub use tags::TagsResource;
pub use todos::TodosResource;
pub use topics::TopicsResource;
pub use users::UsersResource;
pub use variables::VariablesResource;
pub use vulnerabilities::VulnerabilitiesResource;
pub use wikis::WikisResource;
