//! Módulo que contém todos os tipos de dados (structs, enums, type aliases)
//! usados para representar recursos da API GitLab, organizados por domínio.

mod access_levels;
mod access_request;
mod access_token;
mod audit_event;
mod badge;
mod base;
mod board;
mod branch;
mod broadcast_message;
mod ci_lint;
mod ci_variable;
mod commit;
mod container_registry;
mod custom_attribute;
mod deploy_key;
mod deploy_token;
mod deployment;
mod discussion;
mod draft_note;
mod emoji;
mod environment;
mod epic;
mod event;
mod feature_flag;
mod freeze_period;
mod group;
mod group_hook;
mod group_iteration;
mod group_push_rule;
mod group_variable;
mod group_wiki;
mod import_export;
mod integration;
mod invitation;
mod issue;
mod issue_link;
mod job;
mod key;
mod label;
mod license_info;
mod markdown;
mod member;
mod merge_request;
mod merge_train;
mod milestone;
mod namespace;
mod note;
mod notification_setting;
mod oauth;
mod package;
mod package_composer;
mod package_conan;
mod package_debian;
mod package_go_proxy;
mod package_helm;
mod package_maven;
mod package_npm;
mod package_nuget;
mod package_pypi;
mod package_rubygems;
mod package_terraform_modules;
mod package_type;
mod page;
mod personal_access_token;
mod pipeline;
mod pipeline_schedule;
mod pipeline_trigger;
mod project;
mod project_hook;
mod protected_branch;
mod protected_environment;
mod protected_tag;
mod release;
mod remote_mirror;
mod repository_file;
mod repository_tree;
mod resource_event;
mod runner;
mod search;
mod setting;
mod snippet;
mod system_hook;
mod tag;
mod template;
mod todo;
mod topic;
mod user;
mod vulnerability;
mod wiki;

pub use access_levels::*;
pub use access_request::*;
pub use access_token::*;
pub use audit_event::*;
pub use badge::*;
pub use base::*;
pub use board::*;
pub use branch::*;
pub use broadcast_message::*;
pub use ci_lint::*;
pub use ci_variable::*;
pub use commit::*;
pub use container_registry::*;
pub use custom_attribute::*;
pub use deploy_key::*;
pub use deploy_token::*;
pub use deployment::*;
pub use discussion::*;
pub use draft_note::*;
pub use emoji::*;
pub use environment::*;
pub use epic::*;
pub use event::*;
pub use feature_flag::*;
pub use freeze_period::*;
pub use group::*;
pub use group_hook::*;
pub use group_iteration::*;
pub use group_push_rule::*;
pub use group_variable::*;
pub use group_wiki::*;
pub use import_export::*;
pub use integration::*;
pub use invitation::*;
pub use issue::*;
pub use issue_link::*;
pub use job::*;
pub use key::*;
pub use label::*;
pub use license_info::*;
pub use markdown::*;
pub use member::*;
pub use merge_request::*;
pub use merge_train::*;
pub use milestone::*;
pub use namespace::*;
pub use note::*;
pub use notification_setting::*;
pub use oauth::*;
pub use package::*;
pub use package_composer::*;
pub use package_conan::*;
pub use package_debian::*;
pub use package_go_proxy::*;
pub use package_helm::*;
pub use package_maven::*;
pub use package_npm::*;
pub use package_nuget::*;
pub use package_pypi::*;
pub use package_rubygems::*;
pub use package_terraform_modules::*;
pub use package_type::*;
pub use page::*;
pub use personal_access_token::*;
pub use pipeline::*;
pub use pipeline_schedule::*;
pub use pipeline_trigger::*;
pub use project::*;
pub use project_hook::*;
pub use protected_branch::*;
pub use protected_environment::*;
pub use protected_tag::*;
pub use release::*;
pub use remote_mirror::*;
pub use repository_file::*;
pub use repository_tree::*;
pub use resource_event::*;
pub use runner::*;
pub use search::*;
pub use setting::*;
pub use snippet::*;
pub use system_hook::*;
pub use tag::*;
pub use template::*;
pub use todo::*;
pub use topic::*;
pub use user::*;
pub use vulnerability::*;
pub use wiki::*;
