//! Módulo que contém todos os tipos de dados (structs, enums, type aliases)
//! usados para representar recursos da API GitLab, organizados por domínio.

mod access_levels;
mod base;
mod branch;
mod commit;
mod deploy_key;
mod discussion;
mod environment;
mod event;
mod group;
mod issue;
mod job;
mod label;
mod member;
mod merge_request;
mod milestone;
mod note;
mod oauth;
mod pipeline;
mod pipeline_schedule;
mod project;
mod release;
mod repository_file;
mod runner;
mod search;
mod tag;
mod todo;
mod user;
mod wiki;

pub use access_levels::*;
pub use base::*;
pub use branch::*;
pub use commit::*;
pub use deploy_key::*;
pub use discussion::*;
pub use environment::*;
pub use event::*;
pub use group::*;
pub use issue::*;
pub use job::*;
pub use label::*;
pub use member::*;
pub use merge_request::*;
pub use milestone::*;
pub use note::*;
pub use oauth::*;
pub use pipeline::*;
pub use pipeline_schedule::*;
pub use project::*;
pub use release::*;
pub use repository_file::*;
pub use runner::*;
pub use search::*;
pub use tag::*;
pub use todo::*;
pub use user::*;
pub use wiki::*;
